### ISSUE TITLE
SALodLights.ini - StaticSunSize always enabled

### ISSUE THREAD

**Issue by WeedSR** [ThirteenAG/III.VC.SA.IV.Project2DFX#1]
Even if parameter "Enable" in "[DrawDistanceChanger]" is disabled.

**Comment by ThirteenAG** [comment]
Well, of course, because it's not directly related to it. Set StaticSunSize to 0.0 and it will be disabled.

**Comment by WeedSR** [comment]
Ok. Thanks!

**Comment by ThirteenAG** [comment]
No problem.
