### ISSUE TITLE
VC PreloadLODs

### ISSUE THREAD

**Issue by C-500** [ThirteenAG/III.VC.SA.IV.Project2DFX#14]
PreloadLODs (PreloadLODs = 1) работает некорректно: вроде и работает, но между островами все равно присутствуют короткие сплэши.

**Comment by ThirteenAG** [comment]
Там немножко доделать надо, просто руки не дошли. Исправлю потом.

**Comment by C-500** [comment]
Прошу прощения за небывалую наглость, но нет ли каких-нибудь новостей (или хотя бы приблизительных сроков) относительно обновления четвертой версии?..
Пока жду пользуюсь версией 3.3, но похоже она чутка портит сохранения...

**Comment by ThirteenAG** [comment]
Пока нет.
