### ISSUE TITLE
GTAIII exe version

### ISSUE THREAD

**Issue by Failure13** [ThirteenAG/III.VC.SA.IV.Project2DFX#16]
What's the reason of 1.0 only?
Any plans to support 1.1 or steam?

**Comment by ThirteenAG** [comment]
Downgrading to 1.0 exe - 5 seconds.
Making support for 1.1 and steam - hours of work.
No, there's no plans for 1.1 or steam support .

**Comment by Remint32** [comment]
> Downgrading to 1.0 exe - 5 seconds. Making support for 1.1 and steam - hours of work. No, there's no plans for 1.1 or steam support .

Where can I downgrade to 1.0 in 5 seconds without getting a bunch of viruses? Can you recommend a site? Or do I have to search for and sift through suitable torrents while having the licensed binaries?
