### ISSUE TITLE
[IV] Crash

### ISSUE THREAD

**Issue by ThirteenAG** [ThirteenAG/III.VC.SA.IV.Project2DFX#17]
http://gtaforums.com/topic/573478-project2dfx/page-101#entry1069361874

**Comment by ZT-1** [comment]
I can confirm that the same issue reported there also happens to me. It also crashes when the game is loading the second cutscene for the mission First Date. You can skip the first cutscene, but after it starts loading it will crash there.
Saves before these two: 
[ivsaves.zip](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/files/1826802/ivsaves.zip)

**Comment by ThirteenAG** [comment]
I think I looked into it before and couldn't reproduce.

**Comment by ZT-1** [comment]
[GTAIV.exe.20180319163413.zip](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/files/1826842/GTAIV.exe.20180319163413.zip)

**Comment by ThirteenAG** [comment]
Try to disable that: https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/blob/master/data/IVLodLights/IVLodLights.ini#L10
Just set to 0.0. Doesn't look like the crash is directly related to the code, so this is my best guess.

**Comment by ThirteenAG** [comment]
Actually it may not work that way, this one is hardcoded kinda, check with this version: https://transfer.sh/5EaVo/IVLodLights.asi

**Comment by ZT-1** [comment]
So I set LamppostsDrawDistance to 0.0 with the previous version and it didn't crash. Then I set it back to 300.0 with the new version and it also didn't crash.

**Comment by ThirteenAG** [comment]
I guess the game hits a certain limit of something with increased draw distance. I'll remove that option tomorrow.

**Comment by ZT-1** [comment]
Maybe it could be changed with a limit adjuster?

**Comment by ThirteenAG** [comment]
I guess.

**Comment by ThirteenAG** [comment]
Reuploaded without version change, thanks for testing.
