### ISSUE TITLE
No LODS/Weird draw distance even with vanilla game after installing this mod 

### ISSUE THREAD

**Issue by NitrousGTR** [ThirteenAG/III.VC.SA.IV.Project2DFX#20]
So, i installed this mod in my friend pc, [San andreas], and it could run it, (low fps), so we removed it, all the files, but then, even without the files, the game has no lods, and weird draw distance, and looking from above there are "holes" in the map everywhere, even after removing the files, and even on a vanilla game with no mods! what the hell happened? does this mod edits something else on the PC?, it works great on my PC, but it somehow ruined my friends GTA (Reinstalling doesnt remove the issue, this is very weird)

**Comment by spartaque12** [comment]
did u install asi loader , are u usin exe 1.0 , did u try mixsets ? set in mixsets memorty 2048 and also i recommend u 2 use binthesky_by_DK , Full Stream Radar by LINK/2012 and also u can try Load Whole Map (Junior_Djjr)
