### ISSUE TITLE
How can I decrease the draw distance?

### ISSUE THREAD

**Issue by Blingu** [ThirteenAG/III.VC.SA.IV.Project2DFX#22]
Hi, my computer isn't too good, but I would like to use 2dfx anyways. What I've noticed is the bigger draw distance, that I would like to decrease, but in-game options don't really give a good effect.

**Comment by Blingu** [comment]
Before I've used 2dfx objects like trees, poles from a far distance couldn't be seen, but it was compensated by the timecyc I use, it has a higher farclip than the original one. I would like to have the lights around the city, but still have the old draw distance of everything like it was before installing 2dfx.

**Comment by Blackbird88** [comment]
Unfortunately the default values are too demanding for most PCs so you can try
```
MaxNumberOfLodLights = 1000
DrawDistance = 3.0
```

**Comment by ThirteenAG** [comment]
> Unfortunately the default values are too demanding for most PCs so you can try

Not true, recently replayed III era games with default values at first, then increased draw distance from 800.0 to 8000.0, no issues at all.

**Comment by Blackbird88** [comment]
pffff right
