### ISSUE TITLE
bad color in street

### ISSUE THREAD

**Issue by ajidehak** [ThirteenAG/III.VC.SA.IV.Project2DFX#24]
![untitled1](https://user-images.githubusercontent.com/46330726/50613409-b3078600-0ef2-11e9-8d31-2040aa20ece6.jpg)
hi , see this picture
my street light and all corona color change to many bad color
why that happen
please excuse me for bad english

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/blob/master/data/SALodLights/SALodLights.ini#L44
