### ISSUE TITLE
The latest version for GTA III (v4.3) ships with an outdated version of Limit Adjuster

### ISSUE THREAD

**Issue by 07416** [ThirteenAG/III.VC.SA.IV.Project2DFX#25]
https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/releases/tag/gta3 (released on Apr 13, 2015)

Limit Adjuster has been updated a month ago: https://github.com/ThirteenAG/III.VC.SA.LimitAdjuster/releases

**Comment by ThirteenAG** [comment]
All limit adjusters are up to date, what do you mean exactly?

**Comment by 07416** [comment]
> 
> 
> All limit adjusters are up to date, what do you mean exactly?

I mean that **the Limit Adjuster included in Project2DFX** (last updated in 2015) is clearly out of date. Have I understood correctly?

from `III.Project2DFXv4.3.zip`:

- III.VC.SA.LimitAdjuster.asi
- III.VC.SA.LimitAdjuster.ini

**Comment by ThirteenAG** [comment]
2015 date you refer to is the date GitHub release was made. The archives uploaded to it internally called assets and have nothing to do with that date. Limit adjuster asi is the same in all archives, July 17th version.

**Comment by Zanmato27** [comment]
Does that have to with the weird things I'm experiencing with this new version of the Limit Adjuster because it is breaking mods like the Xbox cars and TheHero's Skin & Bones.

**Comment by ViperAcidZX** [comment]
I'm seeing the same problem relating to the Xbox cars and Skin & Bones with the Limit Adjuster v4.3 files and it's annoying that these issues hasn't been rectified other than using an older version.

**Comment by 07416** [comment]
> 2015 date you refer to is the date GitHub release was made. The archives uploaded to it internally called assets and have nothing to do with that date. Limit adjuster asi is the same in all archives, July 17th version.

I'll close this issue since I was mistaken.

Please create separate issues for the v4.3 bugs.
