### ISSUE TITLE
Some LODs overlapping with interiors

### ISSUE THREAD

**Issue by niltwill** [ThirteenAG/III.VC.SA.IV.Project2DFX#26]
Using VCLodLights with `PreloadLODs = 1` (enabled), it causes these LODs to appear when loading a save game inside the mansion or the hotel:
[https://i.postimg.cc/CLxvZm6v/preloadlod-issue1.jpg](https://i.postimg.cc/CLxvZm6v/preloadlod-issue1.jpg)
[https://i.postimg.cc/ncS3qByn/preloadlod-issue2.jpg](https://i.postimg.cc/ncS3qByn/preloadlod-issue2.jpg)
[https://i.postimg.cc/mZwX20Vz/preloadlod-issue3.jpg](https://i.postimg.cc/mZwX20Vz/preloadlod-issue3.jpg)

It only happens after you load a saved game inside the mansion or the hotel with PreloadLODs enabled. When leaving the interior and re-entering, these LODs no longer appear.

I fixed this by [removing this part from the source file](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/blob/master/source/VCLodLights/dllmain.cpp#L400-L409), recompiled with VS2019 and it no longer displays those LODs after loading a game (inside an interior) that it shouldn't.

The problem is that the developers had overlapped these interiors with certain LOD models of the outside game world, so the LODs you force to display appear like shown in those images (although in certain places or angles only).

[Here is my compiled VCLodLights](https://www.mediafire.com/file/ga6vb8a67koscz3/VCLodLights.zip/file), if you need it.

I'm not sure what you were trying to achieve, but the better solution if you want LODs to appear in interiors would be to change the IPL map files instead.

**Comment by ThirteenAG** [comment]
Thanks, I have no time to tackle with this at the moment, so if more people can test it and decide this is better, I'll remove this code.

**Comment by pmsobrado** [comment]
The files from @niltwill works but I lose several lights if I apply it :(

With @niltwill will version:

![01](https://user-images.githubusercontent.com/17699739/81498243-131af300-92c4-11ea-9bc4-9d1804d855d6.png)
![02](https://user-images.githubusercontent.com/17699739/81498247-18783d80-92c4-11ea-8d0a-971c5b81b441.png)

With normal version (bugged with LOD in interiors):

![03](https://user-images.githubusercontent.com/17699739/81498254-24fc9600-92c4-11ea-80d2-01cf63fa722c.png)
![04](https://user-images.githubusercontent.com/17699739/81498256-26c65980-92c4-11ea-8e85-de87dbbc375a.png)

Also, don't know if related with this mod, but why does it seems like the stadium is missing a part of its LOD texture when far?

![05](https://user-images.githubusercontent.com/17699739/81498288-4cebf980-92c4-11ea-9ed5-17a14d506814.png)
