### ISSUE TITLE
[VC] P2DFX crashes the game

### ISSUE THREAD

**Issue by MotorBoatMan** [ThirteenAG/III.VC.SA.IV.Project2DFX#51]
For some reason after adding the P2DFX plugin the game started crashing giving me an error and after I removed it the game ran just fine.

The error: ![GTA VC Error](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/assets/26368742/324ccd8f-e5ee-4ee0-88fc-33de7e129dcb)

The log: [gta-vc.exe.20231128004449.log](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/files/13481396/gta-vc.exe.20231128004449.log) (the dump is too big to upload)

Game version: v1.0 (No-CD by gimpRus)
Installed plugins: Widescreen Fix + Widescreen Frontend, SilentPatch + SilentPatchDDraw, GInput, SkyGfx, Portable GTA and lastly P2DFX (which causes the crashes)

PC Specs:
CPU: Intel Core i5-8400
GPU: Nvidia GeForce GTX 1080
RAM: 16 GB 3200 MT/s
OS: Windows 10 Pro 22H2

Let me know if you need to know more or if it's something on my end that's causing the crashes.

**Comment by ThirteenAG** [comment]
No idea, it crashes in CStreaming::RemoveLoadedVehicle().

**Comment by MotorBoatMan** [comment]
Is there a way I can help/provide you more helpful info or anything? If there's a way I can help I'll gladly do so, since I have no idea what is causing this issue (I don't even know what the error means as I have no vehicle mods, no mod menus/ZMenu, no CLEO or anything).
Just to be clear the game wasn't modded in the first place, everything being vanilla.
I also did a clean reinstall just to be sure and it's still doing this (I'm using the original retail/disc copy). I also didn't change anything in the config files (both the LimitAdjuster or the LodLights).
I even tested Sharptrails and ParticleEx and the game ran perfectly fine (I even checked if the error was documented on the speedrun.com forum and it isn't).
Could it be because of the No-CD executable? I chose the gimpRus one because the one made by FairLight still has the CD check. I'll try it out and come back with an update if it solves the problem.

**Comment by ThirteenAG** [comment]
I just checked, and same happens to me. I think that's something latest ini fix commit was suppose to fix, but I don't remember if I uploaded new archives. Can you test zip from here?
https://ci.appveyor.com/api/buildjobs/8yfbgap8qsx6xd95/artifacts/data%2FVC.Project2DFXv4.4.zip

**Comment by MotorBoatMan** [comment]
Unfortunately I'm getting the same issue but the weird thing is it took a couple seconds more this time (or so i think).
I'll try to explain everything I did with as much detail as I can in case something helps, so here's what I did:
- I copied all the files to the main directory (where the exe is) instead of the "scripts" folder (like I used to do).

Now the way I test it is as follows:

- First I delete the "userfiles" folder that contains the settings config file and savegames just to be safe.
- I launch RTSS.
- I launch the game and reconfigure the settings.
- I start a new game and go straight to Cortez (since I know that location crashes the game and gives that same error every time).

That's all I can provide for atm, if there's something more I can help with let me know and thanks again for looking into this!

**Comment by ThirteenAG** [comment]
Well, it's something in limit adjuster probably.

**Comment by MotorBoatMan** [comment]
Just out of curiosity, does it crash for you when you use the new build you provided?

**Comment by ThirteenAG** [comment]
In III.VC.SA.LimitAdjuster.ini delete `StaticShadows = 8000` under [VCLIMITS]

**Comment by MotorBoatMan** [comment]
Tested both builds (the release and the provided build) for ~10 minutes and they work just fine now!
Thanks a lot, I guess that solved the issue!

**Comment by MotorBoatMan** [comment]
> Yeah, I just saw a comment in limit adjuster that static shadows for iii/vc may not work. Strange that no one reported this before, since it essentially prevents everything from working.

Cool to know, especially since III doesn't suffer from this issue even with the static shadows.

**Comment by MotorBoatMan** [comment]
I retested it with FramerateVigilante as well and all works fine, I guess the issue has been solved.

**Comment by ThirteenAG** [comment]
I've reuploaded archives with edited ini.
