### ISSUE TITLE
[LCS] Heavy stuttering on the latest version of PPSSPP

### ISSUE THREAD

**Issue by LtFrankDrebin** [ThirteenAG/III.VC.SA.IV.Project2DFX#52]
Hello, ThirteenAG. I noticed that Project2DFX introduces heavy stuttering on the latest build of PPSSPP: both cutscenes and gameplay are affected by it. As soon as I uninstall Project2DFX, the FPS drops are gone. Could you please look into it and check whether you experience the same issues?

**Comment by ThirteenAG** [comment]
Hm, it appears that I do. Thought the code haven't changed in 9 months, there was only a sdk update in august. Maybe a ppsspp regression?

**Comment by ThirteenAG** [comment]
I think I have stutters even without the mod :/

**Comment by LtFrankDrebin** [comment]
I've checked the latest version. Unfortunately, the perfomance is still bad on my end: as soon as lod lights activate during the evening, my framerate drops from 30 to 14-15 FPS. Only your widescreen fix and Project2DFX were installed. The first cutscene where Tony gets off a bus still runs at 12-13 FPS too.

**Comment by ThirteenAG** [comment]
You need to increase CPU clock in settings. If that doesn't help, then you don't have the device powerful enough.

**Comment by LtFrankDrebin** [comment]
Thank you for the tip, ThirteenAG. I increased CPU clock to 1000 and enabled every option in the perfomance section of the PPSSPP options. Now I have stable 30 FPS at night, the game seems to work as it should. This topic can be closed now.

**Comment by LtFrankDrebin** [comment]
By the way, ThirteenAG, could you tell me whether it's possible to add "MinDrawDistanceOnTheGround" option from the PC version of Project2DFX to PPSSPP and PCSX2? The only major annoyance I'm experiencing with LCS and VCS on those emulators is low draw distance and the resulting constant pop-in of objects, cars & pedestrians. If only Project2DFX could fix that issue...

**Comment by ThirteenAG** [comment]
No.
