### ISSUE TITLE
About Version Numbers

### ISSUE THREAD

**Issue by 1234G-G4321** [ThirteenAG/III.VC.SA.IV.Project2DFX#55]
@ThirteenAG Is version numbers remove? if yes then why?

**Comment by ThirteenAG** [comment]
No reason to have them as these mods are not actively updated.

**Comment by Remint32** [comment]
@ThirteenAG Please keep version control; I've run into a problem for which there are no clear answers, and I can't even quickly compare versions without having to check the changelogs on GitHub every time to figure out the differences while troubleshooting.
